// <auto-generated />
namespace TechTashWebApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class firstone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstone));
        
        string IMigrationMetadata.Id
        {
            get { return "202105190540453_firstone"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
